INSERT INTO genus 
(genus_name, image) 
VALUES 
('Frie','genus/Frieseomelitta.jpg'),
('Lestri','genus/Lestrimelitta.jpg'),
('Meli','genus/Melipona.jpg'),
('Pleb','genus/Pleb.jpg'),
('Tetra','genus/Tetragonisca.jpg'),
('Trigo','genus/Trigona.jpg');


INSERT INTO species (genus_id, species_name) VALUES (1,'Frieseomelitta dispar'),
(1,'Frieseomelitta doederleini'),
(1,'Frieseomelitta flavicornis'),
(1,'Frieseomelitta francoi'),
(1,'Frieseomelitta freiremaiai'),
(1,'Frieseomelitta languida'),
(1,'Frieseomelitta lehmanni'),
(1,'Frieseomelitta longipes'),
(1,'Frieseomelitta meadewaldoi'),
(1,'Frieseomelitta nigra'),
(1,'Frieseomelitta paranigra'),
(1,'Frieseomelitta paupera'),
(1,'Frieseomelitta portoi'),
(1,'Frieseomelitta silvestrii'),
(1,'Frieseomelitta trichocerata'),
(1,'Frieseomelitta varia'),
(2,'Lestrimelitta catira(Gonzalez and Griswold, 2012)'),
(2,'Lestrimelitta chacoana(Roig-Alsina, 2010)'),
(2,'Lestrimelitta chamelenis(Ayala, 1999)'),
(2,'Lestrimelitta ciliata(Marchi and Melo, 2006)'),
(2,'Lestrimelitta danuncia(Oliveira and Marchi, 2005)'),
(2,'Lestrimelitta ehrhardti(Friese, 1931)'),
(2,'Lestrimelitta glaberrima(Oliveira and Marchi, 2005)'),
(2,'Lestrimelitta glabrata(Camargo and Moure, 1990)'),
(2,'Lestrimelitta guyanensis(Roubik, 1980)'),
(2,'Lestrimelitta huilensis(Gonzalez and Griswold, 2012)'),
(2,'Lestrimelitta limao (Smith, 1863) –irati'),
(2,'Lestrimelitta maracaia(Marchi and Melo, 2006)'),
(2,'Lestrimelitta monodonta( Camargo and Moure, 1990)'),
(2,'Lestrimelitta mourei(Oliveira and Marchi, 2005)'),
(2,'Lestrimelitta nana(Melo, 2003)'),
(2,'Lestrimelitta niitkib(Ayala, 1999)'),
(2,'Lestrimelitta opita(Gonzalez and Griswold, 2012)'),
(2,'Lestrimelitta rufa(Friese, 1903)'),
(2,'Lestrimelitta rufipes(Friese, 1903)'),
(2,'Lestrimelitta similis(Marchi and Melo, 2006)'),
(2,'Lestrimelitta spinosa( Marchi and Melo, 2006)'),
(2,'Lestrimelitta sulina( Marchi and Melo, 2006)'),
(2,'Lestrimelitta tropica( Marchi and Melo, 2006)'),
(3,'Melipona beecheii Bennett'),
(3,'Melipona bicolor (Lepeletier, 1836) – guarupu, guaraipo'),
(3,'Melipona capixaba (Moure & Camargo, 1994)'),
(3,'Melipona compressipes – tiúba'),
(3,'Melipona compressipes manaosensis – jupará'),
(3,'Melipona fasciata Latreille, 2008'),
(3,'Melipona fuscipes Friese, 1900 (Latreille, 1811)'),
(3,'Melipona fuliginosa (Latreille, 1811) – manduri-preto'),
(3,'Melipona interrupta – jandaíra'),
(3,'Melipona marginata Lepeletier, 1836 – manduri, manduri menor, mandurim, minduri, gurupu-do-miúdo, taipeira'),
(3,'Melipona mimetica'),
(3,'Melipona quadrifasciata (Lepeletier) – mandaçaia, amanaçaia, manaçaia, uruçu'),
(3,'M. q. anthidioides'),
(3,'Melipona quinquefasciata (Lepeletier) – mandaçaia-da-terra, mandaçaia-do-chão, uruçu-do-chão'),
(3,'Melipona ruficrus – irapuá'),
(3,'Melipona rufiventris (Lepeletier) – uruçu-amarela, tuiuva, tujuba, bugia'),
(3,'M. r. paraensis – uruçu-boca-de-ralo'),
(3,'Melipona scutellaris Latreille, 1811 – uruçu-nordestina, uruçu'),
(3,'Melipona seminigra'),
(3,'M. s. merrillae – boca-de-renda'),
(3,'Melipona subnitida – jandaíra'),
(4,'P. alvarengai'),
(4,'P. catamarcensis'),
(4,'P. cora'),
(4,'P. domiciliorum'),
(4,'P. droryana'),
(4,'P. emerina'),
(4,'P. flavocincta'),
(4,'P. franki'),
(4,'P. frontalis'),
(4,'P. fulvopilosa'),
(4,'P. goeldiana'),
(4,'P. intermedia'),
(4,'P. jatiformis'),
(4,'P. julianii'),
(4,'P. kerri'),
(4,'P. llorentei'),
(4,'P. lucii'),
(4,'P. malaris'),
(4,'P. manantlensis'),
(4,'P. margaritae'),
(4,'P. melanica'),
(4,'P. meridionalis'),
(4,'P. mexica'),
(4,'P. minima'),
(4,'P. molesta'),
(4,'P. mosquito'),
(4,'P. moureana'),
(4,'P. nigriceps'),
(4,'P. parkeri'),
(4,'P. peruvicola'),
(4,'P. phrynostoma'),
(4,'P. poecilochroa'),
(4,'P. pulchra'),
(4,'P. remota'),
(4,'P. saiqui'),
(4,'P. tica'),
(4,'P. tobagoensis'),
(4,'P. variicolor'),
(4,'P. wittmanni'),
(5,'\" \"'),
(6,'Trigona barrocoloralensis'),
(6,'Trigona branneri—Mato Grosso (BR)'),
(6,'Trigona carbonaria—Queensland (AU)'),
(6,'Trigona chanchamayoensis—Mato Grosso (BR)'),
(6,'Trigona cilipes—América'),
(6,'Trigona collina—Thailand'),
(6,'Trigona corbina—América (Mesoámerica-Costa Rica)'),
(6,'Trigona corvina - Central and South America'),
(6,'Trigona iridipennis—India, Sri Lanka'),
(6,'Trigona ferricauda—América'),
(6,'Trigona fuscipennis'),
(6,'Trigona fulviventris—México.'),
(6,'Trigona fuscipennis—México a Brasil.'),
(6,'Trigona hockingsi—(AU)'),
(6,'Trigona hyalinata—Mato Grosso (BR)'),
(6,'Trigona minangkabau'),
(6,'Trigona nigerrima—América (México, Costa Rica).'),
(6,'Trigona nigra—México.'),
(6,'Trigona pallens—América'),
(6,'Trigona recursa—Mato Grosso (BR)'),
(6,'Trigona siLvestriana—América (Costa Rica)'),
(6,'Trigona spinipes-arapuá (BR)');